#!/usr/bin/awk -f

# Filter csv file by value 

# zcat ~/ct_tariffline_unlogged_2014.csv.gz | data-raw/filterinlinux | uniq | gzip > ~/tl2014.csv.gz


BEGIN { 
  FS = ",";
  OFS = ",";
chaps["01"]== ""
chaps["02"]== ""
chaps["03"]== ""
chaps["04"]== ""
chaps["05"]== ""
chaps["06"]== ""
chaps["07"]== ""
chaps["08"]== ""
chaps["09"]== ""
chaps["10"]== ""
chaps["11"]== ""
chaps["12"]== ""
chaps["13"]== ""
chaps["14"]== ""
chaps["15"]== ""
chaps["16"]== ""
chaps["17"]== ""
chaps["18"]== ""
chaps["19"]== ""
chaps["20"]== ""
chaps["21"]== ""
chaps["22"]== ""
chaps["23"]== ""
chaps["24"]== ""
chaps["33"]== ""
chaps["35"]== ""
chaps["38"]== ""
chaps["40"]== ""
chaps["41"]== ""
chaps["42"]== ""
chaps["43"]== ""
chaps["50"]== ""
chaps["51"]== ""
chaps["52"]== ""
chaps["53"]== ""

}
{ if ($1 in chaps) print $1, $2, $3, $6, $8 }


